---
title: "FinalAnalysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# If you don't have one or both of these these, use install.packages()

# install.packages('arcos')
library(tidyverse)
library(janitor)
library(lubridate)
library(arcos)
library(scales)
library(ggrepel)
library(tidycensus)
library(tigris)
install.packages('maps')
library(maps)
install.packages('corrr')
library(corrr)
```

```{r}
# store a password as an object called key
key <- "uO4EK6I"
```

```{r}
# 1. Data to find state with the highest average pills per person.

state_population_per_year <- read_csv(file="data/state_population_per_year.csv")

highest_pills %>%
  group_by(buyer_state) %>%
  summarise(total_pills=sum(dosage_unit)) %>%
  full_join(state_population_per_year, by="buyer_state") %>%
  mutate(average_pills_person = round((total_pills/population_average),2)) %>%
  arrange(desc(average_pills_person))

# The top 3 states we WV, KY and SC.
```

```{r}
# Let's pull in new useful data that will further explain the infant opioid addiction and the perscriptions women have been prescribed.

neonatal_abstinence_syndrome <- read_csv(file="data/Neonatal_Abstinence_Syndrome.csv")

privately_insured_women <- read_csv(file="data/Privately_Insured_Women.csv")

medicaid_enrolled_women <- read_csv(file="data/Medicaid_Enrolled_Women.csv")
```

```{r}

# 2. Which states have the highest annual change of neonatal abstinence syndrome reported per 1,000 births.

colnames(neonatal_abstinence_syndrome)[colnames(neonatal_abstinence_syndrome)=="X1"] <- "state"

colnames(neonatal_abstinence_syndrome)[colnames(neonatal_abstinence_syndrome)=="Annual Change"] <- "annual_change"

neonatal_abstinence_syndrome %>%
  arrange(desc(annual_change))

# Vermont, Maine and West Virginia have the highest rate of annual change in the increase of neonatal abstinence syndrome.

# We know that WV has the highest average pills per person with 464.89
# Maine has an average of 299.96 pills per person
# Vermont has an average of 197.89 pills per person

```

```{r}
# Let's pull in the WONDER data for infant deaths and births to get a more general overview on these states

infant_births <- read.csv(file="data/Infant Births - 2016-2018.csv", header=TRUE, sep=",")

infant_deaths <- read.csv(file="data/Infant Deaths - 2007-2017.csv", header=TRUE, sep=",")
```

```{r}
# 3.1 Find the infant births and deaths for Vermont

infant_births %>%
  filter(State.of.Residence == "Vermont") %>%
  arrange(desc(Births))

# We can find the statistic for total number of births in Vermont and the percentage of how many of these births have NAS.
```

```{r}
# 3.2 Find the infant births and deaths for Vermont
infant_deaths %>%
  filter(State == "Vermont") %>%
  arrange(desc(Deaths))

# This data set does not have any information on infant deaths in Vermont.
```

```{r}
# 4.1 Find the infant births and deaths for West Virginia

infant_births %>%
  filter(State.of.Residence == "West Virginia") %>%
  arrange(desc(Births))
```

```{r}
# 4.2 Find the infant births and deaths for Vermont

infant_deaths %>%
  filter(State == "West Virginia") %>%
  arrange(desc(Deaths))

# 14 deaths were linked to maternal issues in West Virginia.
```

```{r}
# 5.1 Find the infant births and deaths for Maine

infant_births %>%
  filter(State.of.Residence == "Maine") %>%
  arrange(desc(Births))

```

```{r}
# 5.2 Find the infant births and deaths for Maine

infant_deaths %>%
  filter(State == "Maine") %>%
  arrange(desc(Deaths))

# # 12 deaths were linked to maternal issues in Maine.
```

```{r}
# I found data that describes the rate of change/growth of Opioid Use Disorder at the time of delivery

opioid_use_disorder <- read.csv(file="data/Opioid_Use_Disorder.csv", header=TRUE, sep=",")
```

```{r}
# 6. Pull the data for Vermont, West Virginia and Maine to see if the correlation is still similar to the NAS data.

opioid_use_disorder %>%
  arrange(desc(annual_change))

# Yes, the data is still similar with Vermont at 5.37, Maine 4.13 and West Virginia at 2.83 annual rate change.

# It seems like there should be more investigating for Vermont because they have a high number of infants with some sort of disorder related to opioids. 

# Even though their average pills per person is smaller, that is probably due to it being a smaller state to WV and Maine.

```

```{r}
# 7. Vermont is a state we want to look into How many pills did they receive annually?

vermont_annual_pills <- combined_buyer_annual(state = "VT", key = key)

vermont_annual_pills %>%
  arrange(desc(DOSAGE_UNIT))

# Chittenden County, VT had 3,230,900 dosage units in 2009. Chittenden County holds the top 3 orders of opioids. Let's look into Chittenden County, VT further.
```

```{r}
# 8. Chittenden County, Vermont ordered the most opioids. Look into the data further.

arcos_county_pills_per_year <- summarized_county_annual(key = key) %>%
  clean_names()

chittenden_pills_per_year <- arcos_county_pills_per_year %>%
  filter(buyer_state == "VT", buyer_county == "CHITTENDEN") %>%
  select(year, dosage_unit)
```

```{r}
# 9. Rate of pills per person by county, specifcally Chittenden County, VT.

county_pills_per_year <- arcos_county_pills_per_year %>%
  select(countyfips, buyer_county, year, dosage_unit, buyer_state)

# Join the arcos_county_pills_per_year by state_population_average to find that number
```

```{r}
#census_api_key("549950d36c22ff16455fe196bbbd01d63cfbe6cf")

# Example: vt <- get_acs(geography = "county", 
              #variables = c(medincome = "B19013_001"), 
              #state = "VT")
```

```{r}
# v17 <- load_variables(2017, "acs5", cache = TRUE)

# View(v17)
```

## CONTINUED NOV. 19 IN-CLASS WORK

```{r}
# 10. Let's pull ARCOS data for Vermont:

vermont_arcos <- read_tsv("data/arcos-vt-statewide-itemized.tsv")
```

```{r}

#11. Find how many pills were sent to Vermont

vermont_arcos %>%
group_by(BUYER_NAME, BUYER_COUNTY, BUYER_ADDRESS1) %>%
summarise(shipments = n(),
total_pills = sum(DOSAGE_UNIT)) %>%
arrange(desc(total_pills))

# Chittenden and Franklin are the counties that had the most total pills sent to them. HealthDirect Institutional Pharmacy Services Inc. and University of Vermont Medical Center ordered the most opioids

# KPH Healthcare Services Inc in Franklin ordered the most pills

```


```{r}

#12. Find how many pills were sent to Chittenden County

vermont_arcos %>%
filter(BUYER_COUNTY == "CHITTENDEN") %>%
group_by(BUYER_NAME, BUYER_COUNTY, BUYER_ADDRESS1) %>%
summarise(shipments = n(),
total_pills = sum(DOSAGE_UNIT)) %>%
arrange(desc(total_pills))
```


```{r}
# 13. Where were these pills coming from? What state was sending the most?

vermont_arcos %>%
filter(BUYER_COUNTY == "CHITTENDEN") %>%
group_by(REPORTER_NAME, REPORTER_STATE, BUYER_NAME, BUYER_STATE, BUYER_COUNTY) %>%
summarise(shipments = n(),
total_pills = sum(DOSAGE_UNIT)) %>%
arrange(desc(total_pills))

# Cardinal Health from MA delivered the most opioids to Chittenden County, VT.

```

```{r}
# Is there any more information we can find on the University of Vermont Medical Center and their opioid prescription trends?

```

```{r}

county_pills_per_year <- arcos_county_pills_per_year %>%
  select(countyfips, buyer_county, buyer_state, year, dosage_unit)

county_pills_per_year %>%
  filter(buyer_state == "VT")

```

```{r}
highest_pills <- summarized_county_annual(key = key) %>%
  arrange(desc(DOSAGE_UNIT)) %>%
  janitor::clean_names(case = "snake")
```

```{r}
 highest_pills %>%
  group_by(buyer_state) %>%
  summarise(total_pills=sum(dosage_unit)) %>%
  full_join(state_population_per_year, by="buyer_state") %>%
  mutate(average_pills_person = round((total_pills/population_average),2)) %>%
  arrange(desc(average_pills_person))
```

```{r}
arcos_county_pills_per_year <- summarized_county_annual(key = key) %>%
  clean_names()
  
```

```{r}
vermont_pills_per_year <- arcos_county_pills_per_year %>%
  filter(buyer_state == "VT")
```

```{r}
nas_roc <- neonatal_abstinence_syndrome %>%
  select(state,`2006`:`2012`) %>%
  rename_at(vars(-state),funs(paste0('nas_',.))) %>%
  mutate_at(vars(-state), funs(as.character(.))) %>%
  #mutate_at(vars(-state), funs(. = case_when(. == "null" ~ NA_character_,
  #                            TRUE ~ as.character(.))))
  mutate(nas_2006 = case_when(nas_2006 == "null" ~ NA_character_,
                              TRUE ~ nas_2006)) %>%
  mutate(nas_2007 = case_when(nas_2007 == "null" ~ NA_character_,
                              TRUE ~ nas_2007)) %>%
  mutate(nas_2008 = case_when(nas_2008 == "null" ~ NA_character_,
                              TRUE ~ nas_2008)) %>%
  mutate(nas_2009 = case_when(nas_2009 == "null" ~ NA_character_,
                              TRUE ~ nas_2009)) %>%
  mutate(nas_2010 = case_when(nas_2010 == "null" ~ NA_character_,
                              TRUE ~ nas_2010)) %>%
  mutate(nas_2011 = case_when(nas_2011 == "null" ~ NA_character_,
                              TRUE ~ nas_2011)) %>%
  mutate(nas_2012 = case_when(nas_2012 == "null" ~ NA_character_,
                              TRUE ~ nas_2012)) %>%
  mutate_at(vars(-state), funs(as.numeric(.)))

  
# Pull list of state name and abbreviations. Load Tigris package for this to work
state_fips <- fips_codes %>%
  group_by(state, state_name) %>%
  summarise(count=n()) %>%
  select(state, state_name)

# Join it to nas_roc
nas_roc <- nas_roc %>%
  left_join(state_fips, by=c("state" = "state_name")) %>%
  select(BUYER_STATE = state.y, everything())

# Get totals by state by year
summarize_state_annual <- summarized_county_annual(key = key) %>%
  group_by(BUYER_STATE, year)%>%
  summarise(total_pills=sum(DOSAGE_UNIT))

# Get state population
state_population_annual <- state_population(key = key)

# Calculate pills per person per year
state_pills_per_person_annual <- summarize_state_annual %>%
  inner_join(state_population_annual) %>%
  mutate(pills_per_person = round((total_pills/population),2))%>%
  select(-total_pills,-population) %>%
  pivot_wider(names_from = "year", values_from = "pills_per_person") %>%
  rename_at(vars(-BUYER_STATE),funs(paste0('ppp_',.)))

#Joining the two data sets to have it one place
nas_ppp <- nas_roc %>%
  inner_join(state_pills_per_person_annual)

glimpse(nas_ppp)

nas_ppp %>%
  select(-BUYER_STATE, -state) %>%
  correlate() %>%
  filter(str_detect(rowname, "ppp")) %>%
  select(rowname:nas_2012)

ggplot(nas_ppp) +
  geom_point(aes(nas_2012, ppp_2006)) +
  labs(x="nas", y="ppp", title="NA", caption = "Source: DEA ARCOS database, via Washington Post", fill="buyer_county") +
  scale_y_continuous(labels = comma) +
  scale_x_continuous(labels = comma) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  geom_smooth(aes(nas_2012, ppp_2006), method = "lm", se = FALSE) +
  geom_text(aes(nas_2012, ppp_2006, label=BUYER_STATE))
```
